---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# A cost comparison of amikacin therapy with bedaquiline, for drug-resistant tuberculosis. How the 2019 WHO recommendations impact UK costs

Prioritisation of oral bedaquiline over the injectable agents in the treatment of multidrug-resistant Tuberculosis (MDR-TB) in the World Health Organisations (WHO) 2019 guidelines prompted this UK analysis of cost implications. Using a known cohort of UK patients treated with an injectable agent, with data available on resource use, costs for the use of amikacin were compared with those for bedaquiline, based on recommended monitoring for bedaquiline. In most scenarios, bedaquiline is close to cost neutral compared with injectable therapy, especially if, as expected, some reduction in duration of admission is possible as a result of more rapid culture conversion.

- The patient costs analysis can be found [here](docs/patient_costs_methods.pdf)
- Details of the Bayesian modellingy using jags can be found [here](docs/Bayesian_methods_and_results.pdf)


## Installation

You can install the released version of costAnalysis from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("costAnalysisv2")
```
